# Generated by Django 5.0.6 on 2024-06-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='comptype',
            field=models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('all-in-one', 'All-in-One PC'), ('other', 'Other')], max_length=20, verbose_name='Computer Type'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, verbose_name='GPU'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Computer Name'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(blank=True, max_length=100, verbose_name='RAM'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
