# Generated by Django 5.0.6 on 2024-06-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.computer'),
        ),
    ]
