# Generated by Django 5.0.6 on 2024-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_comment_options_comment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard', models.CharField(blank=True, max_length=100, verbose_name='Keyboard')),
                ('mouse', models.CharField(blank=True, max_length=100, verbose_name='Mouse')),
                ('monitor1', models.CharField(max_length=100, verbose_name='Monitor 1')),
                ('monitor2', models.CharField(blank=True, max_length=100, verbose_name='Monitor 2')),
                ('monitor3', models.CharField(blank=True, max_length=100, verbose_name='Monitor 3')),
            ],
        ),
    ]
