# Generated by Django 5.0.6 on 2024-06-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_peripherals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard', models.CharField(blank=True, max_length=100, verbose_name='Keyboard')),
                ('mouse', models.CharField(blank=True, max_length=100, verbose_name='Mouse')),
                ('monitor1', models.CharField(max_length=100, verbose_name='Monitor 1')),
                ('monitor2', models.CharField(blank=True, max_length=100, verbose_name='Monitor 2')),
                ('monitor3', models.CharField(blank=True, max_length=100, verbose_name='Monitor 3')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='main_app.computer')),
            ],
        ),
        migrations.DeleteModel(
            name='Peripherals',
        ),
    ]
