# Generated by Django 5.0.6 on 2024-06-27 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_peripheral_delete_peripherals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='owner',
            field=models.ForeignKey(default="6", on_delete=django.db.models.deletion.CASCADE, related_name='computer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
