# Generated by Django 5.0.6 on 2024-06-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_computer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='owner',
        ),
    ]
