# Generated by Django 5.0.6 on 2024-06-27 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_computer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='computer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='main_app.computer'),
        ),
    ]
